Use nuevas_tablas;

CREATE TABLE Academia (
COD_SERVIDOR INT,
NOMBRE VARCHAR(50),
MARCA VARCHAR (50),
MEMORIA INT,
DISCO INT,
PRECIO DECIMAL(5,2),
CPUSs INT,
FECHA_COMPRA DATE);

DESC academia;

ALTER TABLE academia add Descuento INT;

ALTER TABLE academia MODIFY Descuento varchar(2);

ALTER TABLE academia MODIFY Descuento INT;

ALTER TABLE academia MODIFY MARCA INT;

ALTER TABLE academia MODIFY Descuento varchar(1);

ALTER TABLE academia modify Descuento varchar(1) AFTER PRECIO;

DESC academia;

ALTER TABLE academia MODIFY MARCA VARCHAR(75) FIRST;

ALTER TABLE academia CHANGE COLUMN DISCO ALMACENAMIENTO INT;

ALTER TABLE academia MODIFY DESCUENTO DECIMAL (5,2);


ALTER TABLE academia DROP FECHA_COMPRA;

ALTER TABLE academia ADD PRECIO_SERVIDOR 
DECIMAL GENERATED ALWAYS AS (PRECIO - DESCUENTO);

INSERT INTO academia (MARCA, COD_SERVIDOR, NOMBRE, MEMORIA, ALMACENAMIENTO, PRECIO, DESCUENTO, CPUSs) 
			VALUES('SONY', 1, 'Memoria1', 1, 10, 19.99, 5.0, 4);
            
SELECT * FROM academia;